name: API Regression Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '04-api-testing/**' 
  pull_request:
    branches: [ main, master ]
    paths:
      - '04-api-testing/**' 


jobs:
  test:
    timeout-minutes: 10 
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 04-api-testing/playwright-api

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: 04-api-testing/playwright-api/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright API tests
      run: npx playwright test

    - name: Upload API Report
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: api-report
        path: 04-api-testing/playwright-api/playwright-report/
        retention-days: 30

   