name: Deploy Unified Reports
on:
  workflow_run:
    workflows: ["Playwright Tests (with BDD extension)", "API Regression Suite", "Performance Load Tests (k6)"]
    types: [completed]
  workflow_dispatch: # Allows me to run it manually if needed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Structure
        run: mkdir -p public/ui-report public/bdd-report public/api-report public/performance-report

      - name: Copy Dashboard
        run: cp website/index.html public/index.html

      # UI Report
      - name: Download UI Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: playwright.yml
          name: playwright-report
          path: public/ui-report

      # BDD Report
      - name: Download BDD Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: playwright.yml
          name: cucumber-report
          path: temp-bdd # Download to a temporary folder first
      - name: Move BDD Files to Public
        run: |
          
          find temp-bdd -name "index.html" -exec cp {} public/bdd-report/index.html \; || true
          find temp-bdd -name "cucumber_report.json" -exec cp {} public/bdd-report/cucumber_report.json \; || true
          rm -rf temp-bdd

      # API Report
      - name: Download API Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: api-tests.yml
          name: api-report
          path: public/api-report

      # Performance Report
      - name: Download Performance Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: performance.yml
          name: k6-summary-report
          path: public/performance-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages # This creates the hosting branch