name: Performance Load Tests (k6)

on:
  push:
    branches: [ main ]
    paths:
      - '05-performance-k6/**' # Only run when performance files change
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows you to run the test manually from the Actions tab

jobs:
  k6_test:
    name: Run k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: 05-performance-k6/scripts/flows/shopping-flow.js
          flags: --vus 1 --duration 10s # Running as a "Smoke Test" for CI health

      - name: Upload Performance Report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-report
          path: 05-performance-k6/reports/summary.html