name: Playwright Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '03-ui-automation-playwright/**' 
  pull_request:
    branches: [ main, master ]
    paths:
      - '03-ui-automation-playwright/**' 

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci 
      working-directory: 03-ui-automation-playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps 
      working-directory: 03-ui-automation-playwright
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: 03-ui-automation-playwright
    
    - name: Run BDD Cucumber tests
      run: npx cucumber-js bdd-tests/features/**/*.feature --config bdd-tests/cucumber.mjs
      env:
        
        NODE_OPTIONS: "--loader ts-node/esm --no-warnings"
        
      working-directory: 03-ui-automation-playwright/bdd-tests

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: 03-ui-automation-playwright/playwright-report/ 
        retention-days: 30
